# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0e7a012d44d1749b8680b1c7b60258b76f4f2284aa6727c7129889e75f4ff30de9881229673a856f5a9e5a110f879b610cc4895210b13a28bd31f62012fa0815

test:
  secret_key_base: 05a50dd478d3ccbb6f5b38c04563b0045f238111becd40ff1027129f20369ea3812fc58e70d27232913a52719a0a4df0b23e4cec87abf0757213c05995a66bba

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
